config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :art_requests do
    collection do
      get :processing_count
      get :search
    end
    resources :casino_card_art_requests do
      member do
        get :confirmation
      end
    end
  end


  get 'new_specification' => 'art_requests#new_specification'
  resources :users, only: [:create] 
  devise_for :users

  resources :users do
    resources :employees
  end

  resources :card_edges
  resources :card_faces
  resources :card_sizes
  resources :customer_card_backs
  resources :markets
  resources :card_packagings
  resources :card_mfg_units
  resources :card_order_types
  resources :products
  resources :product_types
  resources :card_papers
  resources :card_colors
  resources :card_print_seqs
  resources :card_families
  resources :card_jokers
  resources :card_aces
  resources :jobs
  resources :customers do
    collection do
      get :details
      get :customer_from_csv
      post :customer_from_csv
      get :customer_search
    end
  end
  root to: 'welcome#index'
  get 'artist' => 'artist#index'
  resource :pages do
    collection do
      get :not_authorized
    end
  end


  namespace :api, defaults: {format: 'json'}  do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do

      resources :art_requests
      resources :card_face_types
      resources :card_back_types
      resources :card_ace_types
      resources :card_joker_types
      resources :sales_reps
      resources :customers do 
        collection do 
          get :customer_search
        end
      end
      resources :products do 
        collection do 
          get :details
        end
      end
      resources :artists do
        get '/:id/next_job' => 'artists#next_job'
        get '/:id/on_holds' => 'artist#on_holds'
      end
      get '/artist/:id/nextjob' => 'artists#next_job'
      get '/artist/:id/on_holds' => 'artist2#on_holds'
    end
  end
end

app/models/card_paper.rb
class CardPaper < ApplicationRecord
  acts_as_paranoid

  has_many :jobs
end

app/models/card_paper_type.rb
class CardPaperType < ApplicationRecord

end

app/controllers/card_papers_controller.rb
class CardPapersController < ApplicationController
  before_action :set_card_paper, only: [:show, :edit, :update, :destroy]

  # GET /card_papers
  # GET /card_papers.json
  def index
    @card_papers = CardPaper.all
  end

  # GET /card_papers/1
  # GET /card_papers/1.json
  def show
  end

  # GET /card_papers/new
  def new
    @card_paper = CardPaper.new
  end

  # GET /card_papers/1/edit
  def edit
  end

  # POST /card_papers
  # POST /card_papers.json
  def create
    @card_paper = CardPaper.new(card_paper_params)

    respond_to do |format|
      if @card_paper.save
        format.html { redirect_to @card_paper, notice: 'Card paper was successfully created.' }
        format.json { render :show, status: :created, location: @card_paper }
      else
        format.html { render :new }
        format.json { render json: @card_paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /card_papers/1
  # PATCH/PUT /card_papers/1.json
  def update
    respond_to do |format|
      if @card_paper.update(card_paper_params)
        format.html { redirect_to @card_paper, notice: 'Card paper was successfully updated.' }
        format.json { render :show, status: :ok, location: @card_paper }
      else
        format.html { render :edit }
        format.json { render json: @card_paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /card_papers/1
  # DELETE /card_papers/1.json
  def destroy
    @card_paper.destroy
    respond_to do |format|
      format.html { redirect_to card_papers_url, notice: 'Card paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card_paper
      @card_paper = CardPaper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_paper_params
      params.require(:card_paper).permit(:code, :name, :finish)
    end
end

app/helpers/card_papers_helper.rb
module CardPapersHelper
end

app/views/card_papers/_form.html.haml
= simple_form_for @card_paper do |f|
  = f.input :code
  = f.input :name
  = f.input :finish
  = f.button :submit, "Save"

app/views/card_papers/edit.html.haml
%h1 Editing card_paper

= render 'form'

= link_to 'Show', @card_paper
\|
= link_to 'Back', card_papers_path

app/views/card_papers/index.html.haml
%h1 Listing card papers

= link_to 'New Card paper', new_card_paper_path, class: 'btn btn-primary pull-right'
%table.table.table-bordered
  %thead
    %tr
      %th Code
      %th Name
      %th Finish
      %th
      %th
      %th

  %tbody
    - @card_papers.each do |card_paper|
      %tr
        %td= card_paper.code
        %td= card_paper.name
        %td= card_paper.finish
        %td= link_to 'Show', card_paper
        %td= link_to 'Edit', edit_card_paper_path(card_paper)
        %td= link_to 'Destroy', card_paper, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/card_papers/new.html.haml
%h1 New card paper

= render 'form'

= link_to 'Back', card_papers_path

app/views/card_papers/show.html.haml
%p#notice= notice

%p
  %b Code:
  = @card_paper.code
%p
  %b Name:
  = @card_paper.name
%p
  %b Finish:
  = @card_paper.finish

= link_to 'Edit', edit_card_paper_path(@card_paper)
\|
= link_to 'Back', card_papers_path