config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :art_requests do
    collection do
      get :processing_count
      get :search
    end
    resources :casino_card_art_requests do
      member do
        get :confirmation
      end
    end
  end


  get 'new_specification' => 'art_requests#new_specification'
  resources :users, only: [:create] 
  devise_for :users

  resources :users do
    resources :employees
  end

  resources :card_edges
  resources :card_faces
  resources :card_sizes
  resources :customer_card_backs
  resources :markets
  resources :card_packagings
  resources :card_mfg_units
  resources :card_order_types
  resources :products
  resources :product_types
  resources :card_papers
  resources :card_colors
  resources :card_print_seqs
  resources :card_families
  resources :card_jokers
  resources :card_aces
  resources :jobs
  resources :customers do
    collection do
      get :details
      get :customer_from_csv
      post :customer_from_csv
      get :customer_search
    end
  end
  root to: 'welcome#index'
  get 'artist' => 'artist#index'
  resource :pages do
    collection do
      get :not_authorized
    end
  end


  namespace :api, defaults: {format: 'json'}  do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do

      resources :art_requests
      resources :card_face_types
      resources :card_back_types
      resources :card_ace_types
      resources :card_joker_types
      resources :sales_reps
      resources :customers do 
        collection do 
          get :customer_search
        end
      end
      resources :products do 
        collection do 
          get :details
        end
      end
      resources :artists do
        get '/:id/next_job' => 'artists#next_job'
        get '/:id/on_holds' => 'artist#on_holds'
      end
      get '/artist/:id/nextjob' => 'artists#next_job'
      get '/artist/:id/on_holds' => 'artist2#on_holds'
    end
  end
end

app/models/art_request.rb
class ArtRequest < ApplicationRecord

  # has_and_belongs_to_many :product_types
  # accepts_nested_attributes_for :product_types, allow_destroy: false, reject_if: :all_blank
  #
  # has_many :attachments
  # accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: :all_blank
  #
  # has_many :art_request_specifications
  belongs_to :customer #, required: true
  belongs_to :product #, optional: true
  belongs_to :sales_rep
  belongs_to :artist

  validates :customer_id, presence: true
  validates :product_id, presence: true

  # after_create    :create_product_art_request
  # before_update   :noupdate_product
  # before_destroy  :before_destroy

  has_one :card_art_request
  accepts_nested_attributes_for :card_art_request, allow_destroy: true, reject_if: :all_blank

  
  def self.search(flag,q)
    case flag 
      when "cust_name"
        joins(:customer).where("lower(customers.name) like (?)", "%#{q.downcase}%").order("id DESC")
      when "cust_id"
        joins(:customer).where("lower(customers.sage_id) like (?)", "%#{q.downcase}%").order("id DESC")
      when "art_id"
        where(id: q).order("id DESC")
      when "prod_id"
        []
      else
        []
    end
  end

  def product_art_request!
    request_class = product.product_request_class.constantize
    request_class.for_art_request!(self.id)
  end

  def product_art_request
    request_class = product.product_request_class.constantize
    request_class.for_art_request(self.id)
  end

  def requesting_customer=(new_customer)
    unless new_customer.class == Customer
      raise NotCustomerClassError.new('Customer is not a Customer Class', new_customer.class.to_s)
    end
    if new_customer.id == nil
      raise CustomerNotFoundError.new('Customer must be saved before attaching')
    end
    self.customer_id = new_customer.id
  end


  def requesting_customer
    raise CustomerNotFoundError.new('Customer has not been set yet') if customer == nil
    return customer
  end

  def ArtRequest.for_customer(id)
    request = ArtRequest.where(:customer_id => id)
    #request = ArtRequest.find(:all, :conditions => {customer_id => id})
    raise CustomerNotFoundError.new('Customer did not request ay art') if request.count == 0
    request
  end


  def ArtRequest.next(artist_id)
    artist = Artist.find(artist_id)
    artist.next_job
  end


  def ArtRequest.held_requests(artist_id)
    artist = Artist.find(artist_id)
    artist.on_holds
  end

  def ArtRequest.held_request(artist_id, job_id)
    artist = Artist.find(artist_id)
    artist.on_hold(job_id)

  end

  private

  # create the proper product_art_request for proper specs
  # Exampe.  If the request product is 'Casino Cards' then the product_art_request_class would be 'cards_art_request'.
  # create the record and put this record id in it
  def create_product_art_request
    request_class = product.product_request_class.constantize
    request = request_class.new(art_request_id: self.id)
    request.save!
  end

  def product_request
    request_class = product.product_request_class.constantize
    request = request_class.where(["art_set_id = :art_request_id", {art_request_id: self.id}])

  end
  # do not allow the distruction of an art request that still
  def before_destroy

  end

end


class NotCustomerClassError < StandardError

  def initialize(msg='Not a customer CLASS', data='')
    @data = data
    super(msg)
  end
end

class CustomerNotFoundError < StandardError
  attr_accessor :data
  def initialize(msg='Customer not found', data='')
    @data = data
    super(msg)
  end
end

app/controllers/api/v1/art_requests_controller.rb
class Api::V1::ArtRequestsController < Api::V1::ApiController
  
  before_action :set_art_request, only: [:show, :edit, :update, :destroy]

  api :GET, '/art_requests', 'List of ArtRequests'
  def index
    @art_requests = ArtRequest.limit(10).order('id DESC')
    render 'api/v1/art_requests/index'
  end

  api :POST, '/art_requests', 'Create Art Request'
  description 'Create Art Request'
  # param :art_request, Hash, desc: 'ArtRequest Information', :required => true do
  #   param :product_id, String, desc: 'Product Info'
  # end

  def create
    @customer = Customer.find(params[:art_request][:customer_id])
    @art_request = @customer.art_requests.new(art_request_params)
    
    if @art_request.save
      render '/api/v1/art_requests/show', status: :created
    else
      errors = @art_request.errors.full_messages
      render json: {:error => errors}, status: :unprocessable_entity
    end

  end

  api :PATCH, '/art_requests/:id', 'Update ArtRequest'
  description 'Update ArtRequest'
  param :art_request, Hash, desc: 'ArtRequest Info', :required => true do
    param :product_id, String, desc: 'Product Info' 
  end

  def update
    if @art_request.update(art_request_params)
      render '/api/v1/art_requests/show', status: :ok
    else
      errors = @art_request.errors.full_messages
      render json: {:error => errors}, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_art_request
    @art_request = ArtRequest.find(params[:id])
  end

  def art_request_params
    params.require(:art_request).permit(:id,:product_id, :art_requested_date, :shipment_date, :customer_id, :customer_details, :customer_name, :customer_phone, :customer_email, :art_requested_by, :ship_date, :comments,
      product_type_ids: [],card_art_request_attributes: [:id, :design_id, :card_stock_id,:card_type_id, card_face_specs_attributes: [:id, :face_type_id,:color,:ace_id, :joker_id, :comments],
      card_back_specs_attributes: [:id, :back_type_id, :comments, :color]] ,attachments_attributes: [:id, :content, :_destroy])
     # 
  end
end

app/controllers/art_requests_controller.rb
class ArtRequestsController < ApplicationController
  before_action :set_art_request, only: [:show, :edit, :update, :destroy]

  # GET /art_requests/processing_count
  def processing_count
    render plain: ArtRequestSpecification.where(card_side_id: params[:side]).select{|ars| ars.casino_card_art_request.confirmed }.count.to_s
  end

  # GET /art_requests
  # GET /art_requests.json
  def index
    @art_requests = ArtRequest.all
  end

  def search
    @q = params[:search]
    @flag = params[:search_flag]
    @art_requests = ArtRequest.search(@flag,@q)

    respond_to do |format|
      format.html { render 'index'}
    end
  end

  # GET /art_requests/1
  # GET /art_requests/1.json
  def show
  end

  # GET /art_requests/new
  def new
    @flag = params[:flag] || params[:customer][:flag]
    if @flag == "CUSTOMER"
      @customer = Customer.new
    elsif @flag == "NEW_CUST"
      @customer = Customer.new(customer_params)
      @customer.save
      @art_request = @customer.art_requests.new
      @card_art_request = @art_request.build_card_art_request
      @card_art_request.card_face_specs.build
      @card_art_request.card_back_specs.build
      @product = Product.details

    elsif @flag == "CUST_ART_REQ"
      @customer = Customer.find(params[:customer][:id])
      @art_request = @customer.art_requests.new
      @card_art_request = @art_request.build_card_art_request
      @product = Product.details
    else
      @art_request = ArtRequest.new
    end
  end

  def new_specification
    binding.pry
    @card_art_request = params[:ca_id]

    respond_to do |format|
      format.js {}
    end
  end

  # GET /art_requests/1/edit
  def edit
    @card_art_request = CardArtRequest.for_art_request(@art_request)
    #binding.pry
    @product = Product.details
  end

  # POST /art_requests
  # POST /art_requests.json
  def create
    @customer = Customer.find(params[:art_request][:customer_id])
    @art_request = @customer.art_requests.new(art_request_params)
    
    #binding.pry
    respond_to do |format|
      if @art_request.save
        format.html { redirect_to art_requests_path, notice: 'Art request was successfully created.' }
        format.json { render :show, status: :created, location: @art_request }
      else
        format.html { render :new }
        format.json { render json: @art_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /art_requests/1
  # PATCH/PUT /art_requests/1.json
  def update
    respond_to do |format|
      if @art_request.update(art_request_params)
        format.html { redirect_to art_requests_path , notce: 'Art request was successfully updated.' }
        format.json { render :show, status: :ok, location: @art_request }
      else
        format.html { render :edit }
        format.json { render json: @art_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /art_requests/1
  # DELETE /art_requests/1.json
  def destroy
    @art_request.destroy
    respond_to do |format|
      format.html { redirect_to art_requests_url, notice: 'Art request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art_request
      @art_request = ArtRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_request_params
      params.require(:art_request).permit(:id,:product_id, :customer_id, :customer_details, :customer_name, :customer_phone, :customer_email, :art_requested_by, :ship_date, :comments,
        product_type_ids: [],card_art_request_attributes: [:id, :design_id, :card_stock_id,:card_type_id, card_face_specs_attributes: [:id, :face_type_id,:color,:ace_id, :joker_id, :comments],
        card_back_specs_attributes: [:id, :back_type_id, :comments, :color]] ,attachments_attributes: [:id, :content, :_destroy])
       # 
    end

    def customer_params
      params.require(:customer).permit(:sage_id, :name, :address1, :address2, :address3, :contact_name, :contact_email, :contact_phone, :customer_no, :city, :state, :country_code, :sales_preson_no, :zipcode)
    end
end

app/helpers/art_requests_helper.rb
module ArtRequestsHelper
end

app/views/art_requests/_art_request_form.html.haml
.card-panel
  = simple_nested_form_for(@art_request) do |f|
    = f.input :customer_id, :as => :hidden
    .row{:style => "border-bottom: 1px solid #291818"}
      .col.s12
        %span.col.s4
          Customer #:
          = @art_request.customer.sage_id
        %span.col.s4
          Casino:
          = @art_request.customer.name
        %span.col.s4
          Sales Rep:
          = @art_request.sales_rep.name unless @art_request.sales_rep.blank?
    .row
      .col.s12
        %span.col.s4
          Art Requested Date #:
          = @art_request.art_requested_date.strftime("%m/%d/%Y") unless @art_request.art_requested_date.blank?
        %span.col.s4
          Shipment Date:
          = @art_request.shipment_date.strftime("%m/%d/%Y") unless @art_request.shipment_date.blank?
        %span.col.s4
          Attachements:
          = link_to "2", "#"
    .row
      %ul
        %li
          .col.s12.product-header.min-padding
            .col.s3.custom-s3{:style => "margin-right: -51px;"}
              .left.lpad
                Product:
              .left.rpad
                =# f.input :product_id, collection: Product.all.map{|p| [p.name, p.id]}, :label => false
                = f.input :product_id, collection: @product.map{|p| [p[:name], p[:id]] }, :label => false
            .col.s9{:style => "width: 80%;"}
              = f.fields_for :card_art_request do |ca|
                .col.s3.custom-s3
                  .left.lpad
                    Design:
                  .left.rpad
                    = ca.input :design_id, collection: @product[0][:items][0][:items].map{|d| [d[:name], d[:id]]}, :label => false
                .col.s4.custom-s4
                  .left.lpad
                    Card Stock:
                  .left.rpad
                    = ca.input :card_stock_id, collection: @product[0][:items][1][:items][0][:items].map{|d| [d[:name], d[:id]]} , :label => false
                .col.s3.custom-cardtype
                  .left.lpad
                    Card Type:
                  .left.rpad
                    = ca.input :card_type_id, collection: @product[0][:items][2][:items][0][:items].map{|d| [d[:name], d[:id]]}, :label => false
                  .left{:style => "padding-left: 13px;padding-top:9px;clear: both;position: absolute;right: 119px;"}
                    = link_to "Add Specification", "#", :id => "add_spec" if @card_art_request.specs.size > 0
                - @ca = ca
          = render :partial => 'spec_form', :locals => {:ca => @ca , :car => @card_art_request}
    = link_to 'Go Back', art_requests_path , class: 'btn orange'
    = f.submit 'Save', class: 'btn blue right', :id => 'art_request_submit'


                

app/views/art_requests/_back_spec_form.html.haml
%li
  .collapsible-header.specheader
    %span.jtext.spec-space
      = spec_type.capitalize
      &nbsp;
      = "-"
      &nbsp;
      = s.color
    %span.jtext.spec-space
      Art Id: 1235
    %span.jtext.spec-space
      Finished
    %span.jtext.spec-space
      Activity: Approved
  .collapsible-body
    = ca.fields_for :card_back_specs do |bs|
      .row
        .speclines.col.s12
          %span.col.s2
            %ul
              %li.label
                Side: 
              %li
                %select
                  %option{:value => spec_type ,:selected => "selected"}= spec_type.capitalize
                  %option{:value => op_spec_type}= op_spec_type.capitalize
          %span.col.s4
            %ul
              %li.label
                Back Style:
              %li
                = bs.input :back_type_id, collection: CardBackType.all.map{|ft| [ft.name, ft.id]}, :label => false
      .row
        .speclines.col.s12
          %span.col.s6
            Comments
            = bs.input :comments, :label => false
          %span.col.s3
            Back Color:
            = bs.input :color, :collection => [["GOLD","GOLD"],["GREEN","GREEN"]], :label => false, :selected => "GOLD"
            / %span 
            /   Selected Colors
            / %br
            / %span
            /   1.Green
            /   2.Gold
      .row
        .speclines.col.s12
          %span.col.s6
            Reference Attachments
            .chip
              Winnlogbw.png
              %i.close.material-icons close

app/views/art_requests/_face_spec_form.html.haml
%li
  .collapsible-header.specheader
    %span.jtext.spec-space
      = spec_type.capitalize
      &nbsp;
      = "-"
      &nbsp;
      = s.color
    %span.jtext.spec-space
      Art Id: 1235
    %span.jtext.spec-space
      Finished
    %span.jtext.spec-space
      Activity: Approved
  .collapsible-body
    = ca.fields_for :card_face_specs do |fs|
      .row
        .speclines.col.s12
          %span.col.s2
            %ul
              %li.label
                Side: 
              %li
                %select
                  %option{:value => spec_type ,:selected => "selected"}= spec_type.capitalize
                  %option{:value => op_spec_type}= op_spec_type.capitalize
          %span.col.s3
            %ul
              %li.label
                Face Style:
              %li
                = fs.input :face_type_id, collection: CardFaceType.all.map{|ft| [ft.name, ft.id]}, :label => false
                / %select
                  
                /   %option{:selected => "selected", :value => ""} Traditional - GEMACO
                /   %option{:value => "1"} Back
          %span.col.s2
            %ul
              %li.label
                Ace:
              %li
                = fs.input :ace_id, collection: CardAceType.all.map{|ft| [ft.name, ft.id]}, :label => false
                / %select
                /   %option{:disabled => "disabled", :selected => "selected", :value => ""} Gemaco
                /   %option{:value => "1"} Back
          %span.col.s2
            %ul
              %li.label
                Joker:
              %li
                = fs.input :joker_id, collection: CardJokerType.all.map{|ft| [ft.name, ft.id]}, :label => false
                / %select
                /   %option{:disabled => "disabled", :selected => "selected", :value => ""} None
                /   %option{:value => "1"} Back
      .row
        .speclines.col.s12
          %span.col.s6
            Comments
            = fs.input :comments, :label => false
            / %textarea#textarea1{:cols => "50", :rows => "4"}
          %span.col.s3
            Face Color:
            =# fs.input :color, :collection => [["GOLD","GOLD"],["GREEN","GREEN"]], :label => false, :selected => "GOLD", :input_html => {:id => "colorselector_1"}
            %select.selectmenu
              %option{:value => "106", :selected => "selected", "data-style" => "background-color: #ffc800;"}
                GOLD
              %option{"data-color" => "#CD5C5C", :value => "47","data-style" => "background-color: green;"} GREEN


              
            / %select
            /   %option{:disabled => "disabled", :selected => "selected", :value => ""} Gold
            /   %option{:value => "1"} Green
            / %span 
            /   Selected Colors
            / %br
            / %span
            /   1.Green
            /   2.Gold
      .row
        .speclines.col.s12
          %span.col.s6
            Reference Attachments
            .chip
              Winnlogbw.png
              %i.close.material-icons close

app/views/art_requests/_form.html.haml
- if @flag == "CUSTOMER" 
  .customer-from
    = render :partial =>'customers/customer_form', :locals => { :@customer => @customer }
- if @flag == "CUST_ART_REQ"
  .art-req-form
    = render :partial => 'art_request_form', :locals => {:@customer => @customer, :@art_request => @art_request, :@proudct => @product }
- if @flag == "NEW_CUST"
  .art-req-form
    = render :partial => 'art_request_form', :locals => {:@customer => @customer, :@art_request => @art_request, :@proudct => @product }
:css
  .submit-btn{
    clear: both;
    position: absolute;
    top: 14%;
    right: 4%;
  }
  .search-customer{
    position: absolute;
    top: 10px;
    right: 10px;
    cursor: pointer;
  }

app/views/art_requests/_form1.html.haml
.container
  .panel.panel-default
    .panel-heading
      %h3 New Art Request
    .panel-body
      = simple_nested_form_for(@art_request, :html => { :class => 'form-inline'}) do |f|
        = f.error_notification

        .form-inputs
          .panel.panel-section
            .row
              .col-md-4
                = f.input :customer_id, label: 'Customer #:'
              .col-md-4
                = f.input :customer_details, label: 'Customer:', as: :text, input_html: {rows: 3}
              .col-md-4
                .panel.panel-section
                  %legend Contact
                  %table.contact-table 
                    %tr
                      %td
                        %label Name:
                      %td
                        = f.input :customer_name, label: false
                    %tr
                      %td
                        %label Phone:
                      %td
                        = f.input :customer_phone, label: false
                    %tr
                      %td
                        %label Email:
                      %td
                        = f.input :customer_email, label: false
          
          .row
            .col-md-6
              = f.input :art_requested_by, as: :date_time_picker
            .col-md-6
              = f.input :ship_date, as: :date_time_picker


          %br
          .panel.panel-section
            .row
              .col-md-12
                %legend Product Categories
                = f.association :product_types, as: :check_boxes, collection: ProductType.all.to_a, label_method: :name, label: false
          .panel.panel-section
            .row
              .col-md-12
                = f.label "Attachment"
                = f.fields_for :attachments do |a|
                  .col-md-12
                    .col-md-4
                      .pull-right= a.link_to_remove "x", class: 'rounded'
                      - unless a.object.new_record?
                        = a.object.content_file_name
                      - else
                        //= a.input :content, label: false
                = f.link_to_add "Add attachment", :attachments, class: 'btn btn-mini btn-default'
          .panel.panel-section
            .row
              .col-md-12
                %legend Comments
                .input-group-lg
                  = f.input :comments, label: false, input_html: { :cols => 120, :rows => 3}
        .panel.panel-section
          = f.button :submit, "Next >>", class: 'btn btn-primary'
          = link_to "GoBack", :back, class: 'btn btn-default pull-right'
    .panel-footer

app/views/art_requests/_spec_form.html.haml
.col.s12.min-padding{:style => "margin-top: -7px;"}
  %ul.collapsible.new_spec{"data-collapsible" => "accordion"}
    - if ca.object.new_record?
      = render :partial => 'new_spec_form', :locals => {:ca => ca}
    - else
      - car.specs.reverse.each do |s|
        - spec_type,op_spec_type = s.class.name == "CardBackSpec" ? ["back","face"] : ["face","back"]
        - if spec_type == "face"
          = render :partial => 'face_spec_form', :locals => {:ca => ca, :spec_type => spec_type, :op_spec_type => op_spec_type, :s => s}
        - if spec_type == "back"
          = render :partial => 'back_spec_form', :locals => {:ca => ca, :spec_type => spec_type, :op_spec_type => op_spec_type, :s => s}

:javascript
  $("document").ready(function(){
    $("#add_spec").click(function(){
      $(".new_spec").append("")
    })
    $('#colorselector_1').colorselector();


    $.widget( "custom.iconselectmenu", $.ui.selectmenu, {
      _renderItem: function( ul, item ) {

        var li = $( "<li>" ),
          wrapper = $( "<div>", { text: item.label } );
 
        if ( item.disabled ) {
          li.addClass( "ui-state-disabled" );
        }
 
        $( "<span>", {
          style: item.element.attr( "data-style" ),
          "class": "ui-icon " + item.element.attr( "data-class" )
        })
          .appendTo( wrapper );
 
        return li.append( wrapper ).appendTo( ul );
      }
    });


    $( ".selectmenu" )
        .iconselectmenu()
        .iconselectmenu( "menuWidget");

    $(".next").click(function(e){
      e.preventDefault();
      console.log("hello")
      var nextval = $(".selectmenu > option:selected").next().val();
      console.log(nextval);
      $('.selectmenu').selectmenu("value", nextval);
    })
  })
:css 
  .ui-icon, .ui-widget-content .ui-icon{
    background-image: none;
  }

  .ui-menu .ui-icon {
    left: 10.2em;
  }

  option.red:after { background: #c00; }
  #cust option.green:after { background: #0c0; }
  #cust option.blue:after { background: #00c; }

app/views/art_requests/_status.html.haml
%p{:style => "padding-top: 8px;margin-top: 14px;padding-bottom: 0px"}
  %span.custom.bluebarsmall.submitted
  %span.custom.bluecircle=# car.submitted_spec_count
  %span.custom.bluebar.inprogress
  %span.custom.bluecircle=# car.inprogress_spec_count
  %span.custom.bluebar.artfinished
  %span.custom.bluecircle=# car.art_finished_spec_count
  %span.custom.bluebar.pendapproval
  %span.custom.bluecircle=# car.pending_approval_spec_count 
  %span.custom.bluebar.artapproved
  %span.custom.bluecircle=# car.art_approved_spec_count 

  %span.custom.bluebarsmall.bluebarsmalllast

%p{:style => "padding-top: 13px;margin-top: 0px;"}
  .submitted-space.custom
  %span.custom.boldsize
    Submitted
  .inprogress-space.custom
  %span.custom.boldsize
    In Progress
  .artfinished-space.custom
  %span.custom.boldsize
    Artist Finished
  .pendapproval-space.custom
  %span.custom.boldsize
    Pending Approval
  .artapproved-space.custom
  %span.custom.boldsize
    Art Approved
  .printed-space.custom

app/views/art_requests/index.html.haml
.row
  .col.s12
    = form_tag search_art_requests_path, :method => 'get' do
      .col.s2{:style => "padding-top: 18px;"}
        = select_tag :search_flag, options_for_select([["Customer","cust_name"],["Customer ID","cust_id"], ["Art ID","art_id"], ["Product","product"]], @flag)
        / %select{:name => params[:search_flag]}
        /   %option{:disabled => "disabled", :selected => "selected", :value => ""} Customer
        /   %option{:value => "cust_name"} Customer
        /   %option{:value => "cust_id"} Customer ID
        /   %option{:value => "art_id"} Art ID
        /   %option{:value => "prod_id"} Product
      .col.s2
        = text_field_tag :search, params[:search]
      .col.s1{:style => "padding-top: 28px"}
        = submit_tag "GO", :name => nil
        / %button{:type => "submit"} GO
    .col.s2{:style => "padding-top: 28px"}
      View: My Requests
    .col.s2{:style => "padding-top: 28px"}
      Order by: Job Id
    .col.s2{:style => "padding-top: 28px"}
      = link_to new_art_request_path(flag: "CUSTOMER"), class: 'right' do
        New Art request
%ul.cps{"data-collapsible" => "expandable"}
  - @art_requests.each do |ar|
    %li
      .collapsible-header.jheader
        %span.jtext.jcustom-space
          Job Id:
          = ar.id
        %span.jtext.jcustom-space=ar.customer.name
        %span.jtext.jcustom-space
          Status: Submitted
        %span.jtext.jcustom-space
          Artist:
          =ar.sales_rep.name unless ar.sales_rep.blank?
        %span.jtext
          Ship Date:
          =ar.art_requested_date.strftime("%m/%d/%Y") unless ar.art_requested_date.blank?
        %span.edits.right
          %i.material-icons.collap visibility
        %span.edits.right
          = link_to edit_art_request_path(ar) do
            %i.material-icons mode_edit 
      .collapsible-body
        = render partial: 'status', locals: {:car => ar.card_art_request}
        = render partial: 'specs', locals: {:car => ar.card_art_request}
%br

app/views/art_requests/new.html.haml
/ %h1 New art request

= render 'form'

//= link_to 'Back', art_requests_path

app/views/art_requests/new_specification.js.erb
$("#new_specs").append("<%= j(render :partial => 'new_spec_form', :locals => {:ca => @card_art_request}) %>")

app/views/art_requests/show.html.haml
.row
  .col-md-4
    %p
      %b Customer:
      = @art_request.customer_id
  .col-md-4
    %p
      %b Customer details:
      = @art_request.customer_details
  .col-md-4
    %p
      %b Customer name:
      = @art_request.customer_name
    %p
      %b Customer phone:
      = @art_request.customer_phone
    %p
      %b Customer email:
      = @art_request.customer_email
.row
  .col-md-6
    %p
      %b Art requested by:
      = @art_request.art_requested_by
  .col-md-6
    %p
      %b Ship date:
      = @art_request.ship_date
.row
  .col-md-12
    %p
      %b Product types:
      = @art_request.product_types.collect(&:name).join(", ")
.row
  .col-md-12
    %p
      %b Attachments:
      %ul
        - @art_request.attachments.each do |attach|
          %li= link_to attach.content_file_name, attach.content.url
.row
  .col-md-12
    %p
      %b Comments:
      = @art_request.comments

= link_to 'Edit', edit_art_request_path(@art_request)
\|
= link_to 'Back', art_requests_path