config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :art_requests do
    collection do
      get :processing_count
      get :search
    end
    resources :casino_card_art_requests do
      member do
        get :confirmation
      end
    end
  end


  get 'new_specification' => 'art_requests#new_specification'
  resources :users, only: [:create] 
  devise_for :users

  resources :users do
    resources :employees
  end

  resources :card_edges
  resources :card_faces
  resources :card_sizes
  resources :customer_card_backs
  resources :markets
  resources :card_packagings
  resources :card_mfg_units
  resources :card_order_types
  resources :products
  resources :product_types
  resources :card_papers
  resources :card_colors
  resources :card_print_seqs
  resources :card_families
  resources :card_jokers
  resources :card_aces
  resources :jobs
  resources :customers do
    collection do
      get :details
      get :customer_from_csv
      post :customer_from_csv
      get :customer_search
    end
  end
  root to: 'welcome#index'
  get 'artist' => 'artist#index'
  resource :pages do
    collection do
      get :not_authorized
    end
  end


  namespace :api, defaults: {format: 'json'}  do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do

      resources :art_requests
      resources :card_face_types
      resources :card_back_types
      resources :card_ace_types
      resources :card_joker_types
      resources :sales_reps
      resources :customers do 
        collection do 
          get :customer_search
        end
      end
      resources :products do 
        collection do 
          get :details
        end
      end
      resources :artists do
        get '/:id/next_job' => 'artists#next_job'
        get '/:id/on_holds' => 'artist#on_holds'
      end
      get '/artist/:id/nextjob' => 'artists#next_job'
      get '/artist/:id/on_holds' => 'artist2#on_holds'
    end
  end
end

app/models/card_packaging.rb
class CardPackaging < ApplicationRecord
  acts_as_paranoid

  has_many :jobs
end

app/controllers/card_packagings_controller.rb
class CardPackagingsController < ApplicationController
  before_action :set_card_packaging, only: [:show, :edit, :update, :destroy]

  # GET /card_packagings
  # GET /card_packagings.json
  def index
    @card_packagings = CardPackaging.all
  end

  # GET /card_packagings/1
  # GET /card_packagings/1.json
  def show
  end

  # GET /card_packagings/new
  def new
    @card_packaging = CardPackaging.new
  end

  # GET /card_packagings/1/edit
  def edit
  end

  # POST /card_packagings
  # POST /card_packagings.json
  def create
    @card_packaging = CardPackaging.new(card_packaging_params)

    respond_to do |format|
      if @card_packaging.save
        format.html { redirect_to @card_packaging, notice: 'CardPackaging was successfully created.' }
        format.json { render :show, status: :created, location: @card_packaging }
      else
        format.html { render :new }
        format.json { render json: @card_packaging.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /card_packagings/1
  # PATCH/PUT /card_packagings/1.json
  def update
    respond_to do |format|
      if @card_packaging.update(card_packaging_params)
        format.html { redirect_to @card_packaging, notice: 'CardPackaging was successfully updated.' }
        format.json { render :show, status: :ok, location: @card_packaging }
      else
        format.html { render :edit }
        format.json { render json: @card_packaging.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /card_packagings/1
  # DELETE /card_packagings/1.json
  def destroy
    @card_packaging.destroy
    respond_to do |format|
      format.html { redirect_to card_packagings_url, notice: 'CardPackaging was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card_packaging
      @card_packaging = CardPackaging.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_packaging_params
      params.require(:card_packaging).permit(:name, :desc, :item_num)
    end
end

app/views/card_packagings/_form.html.haml
= simple_form_for @card_packaging do |f|
  = f.input :name
  = f.input :desc
  = f.input :item_num
  = f.button :submit, "Save"

app/views/card_packagings/edit.html.haml
%h1 Editing card_packaging

= render 'form'

= link_to 'Show', @card_packaging
\|
= link_to 'Back', card_packagings_path

app/views/card_packagings/index.html.haml
%h1 Listing card packagings
= link_to 'New Packaging', new_card_packaging_path, class: 'btn btn-primary pull-right'

%table.table.table-bordered
  %thead
    %tr
      %th Name
      %th Desc
      %th Item nmbr
      %th
      %th
      %th

  %tbody
    - @card_packagings.each do |card_packaging|
      %tr
        %td= card_packaging.name
        %td= card_packaging.desc
        %td= card_packaging.item_num
        %td= link_to 'Show', card_packaging
        %td= link_to 'Edit', edit_card_packaging_path(card_packaging)
        %td= link_to 'Destroy', card_packaging, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/card_packagings/new.html.haml
%h1 New card packaging

= render 'form'

= link_to 'Back', card_packagings_path

app/views/card_packagings/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @card_packaging.name
%p
  %b Desc:
  = @card_packaging.desc
%p
  %b Item number:
  = @card_packaging.item_num

= link_to 'Edit', edit_card_packaging_path(@card_packaging)
\|
= link_to 'Back', card_packagings_path