config/routes.rb
Rails.application.routes.draw do
  apipie
  resources :art_requests do
    collection do
      get :processing_count
      get :search
    end
    resources :casino_card_art_requests do
      member do
        get :confirmation
      end
    end
  end


  get 'new_specification' => 'art_requests#new_specification'
  resources :users, only: [:create] 
  devise_for :users

  resources :users do
    resources :employees
  end

  resources :card_edges
  resources :card_faces
  resources :card_sizes
  resources :customer_card_backs
  resources :markets
  resources :card_packagings
  resources :card_mfg_units
  resources :card_order_types
  resources :products
  resources :product_types
  resources :card_papers
  resources :card_colors
  resources :card_print_seqs
  resources :card_families
  resources :card_jokers
  resources :card_aces
  resources :jobs
  resources :customers do
    collection do
      get :details
      get :customer_from_csv
      post :customer_from_csv
      get :customer_search
    end
  end
  root to: 'welcome#index'
  get 'artist' => 'artist#index'
  resource :pages do
    collection do
      get :not_authorized
    end
  end


  namespace :api, defaults: {format: 'json'}  do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do

      resources :art_requests
      resources :card_face_types
      resources :card_back_types
      resources :card_ace_types
      resources :card_joker_types
      resources :sales_reps
      resources :customers do 
        collection do 
          get :customer_search
        end
      end
      resources :products do 
        collection do 
          get :details
        end
      end
      resources :artists do
        get '/:id/next_job' => 'artists#next_job'
        get '/:id/on_holds' => 'artist#on_holds'
      end
      get '/artist/:id/nextjob' => 'artists#next_job'
      get '/artist/:id/on_holds' => 'artist2#on_holds'
    end
  end
end

app/models/casino_card_art_request.rb
class CasinoCardArtRequest < ApplicationRecord
  has_many :art_request_specifications
  accepts_nested_attributes_for :art_request_specifications, allow_destroy: true, reject_if: :all_blank

  belongs_to :card_type, class_name: 'CardFamily'
  belongs_to :paper_type, class_name: 'CardPaper'
  belongs_to :art_request
end

app/controllers/casino_card_art_requests_controller.rb
class CasinoCardArtRequestsController < ApplicationController
  before_action :set_casino_card_art_request, only: [:show, :edit, :update, :destroy, :confirmation]
  before_action :set_art_request

  # GET /casino_card_art_requests
  # GET /casino_card_art_requests.json
  def index
    @casino_card_art_requests = CasinoCardArtRequest.all
  end

  # GET /casino_card_art_requests/1
  # GET /casino_card_art_requests/1.json
  def show
  end

  # GET /casino_card_art_requests/new
  def new
    @casino_card_art_request = CasinoCardArtRequest.new
  end

  # GET /casino_card_art_requests/1/edit
  def edit
  end

  def confirmation
    @casino_card_art_request.update_attribute(:confirmed, true)
    redirect_to [@art_request, @casino_card_art_request] 
  end

  # POST /casino_card_art_requests
  # POST /casino_card_art_requests.json
  def create
    @casino_card_art_request = CasinoCardArtRequest.new(casino_card_art_request_params)

    respond_to do |format|
      if @casino_card_art_request.save
        format.html { 
          @confirmation = true
          render :new
        }
        format.json { render :show, status: :created, location: @casino_card_art_request }
      else
        format.html { render :new }
        format.json { render json: @casino_card_art_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casino_card_art_requests/1
  # PATCH/PUT /casino_card_art_requests/1.json
  def update
    respond_to do |format|
      if @casino_card_art_request.update(casino_card_art_request_params)
        format.html { redirect_to [@art_request, @casino_card_art_request], notice: 'Casino card art request was successfully updated.' }
        format.json { render :show, status: :ok, location: @casino_card_art_request }
      else
        format.html { render :edit }
        format.json { render json: @casino_card_art_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casino_card_art_requests/1
  # DELETE /casino_card_art_requests/1.json
  def destroy
    @casino_card_art_request.destroy
    respond_to do |format|
      format.html { redirect_to casino_card_art_requests_url, notice: 'Casino card art request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art_request
      @art_request = ArtRequest.find(params[:art_request_id])
    end
    def set_casino_card_art_request
      @casino_card_art_request = CasinoCardArtRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def casino_card_art_request_params
      params.require(:casino_card_art_request).permit(:customer_id, :customer_details, :customer_name, :customer_phone, :customer_email, :job_no, :paper_type_id, :card_type_id,
        :card_packaging_type_id, :art_request_id,
        art_request_specifications_attributes: [:id, :card_side_id, :face_style_id, :card_edge_id, :packaging_type_id, :first_color_id, :second_color_id, :third_color_id, :forth_color_id, :production_notes, :_destroy] )
    end
end

app/helpers/casino_card_art_requests_helper.rb
module CasinoCardArtRequestsHelper
  def available_colors
    CardColor.all.collect{|cc| [cc.name, cc.id]} + [["Custom", "Custom"]]
  end
end

app/views/casino_card_art_requests/_card_color_modal.html.haml
#cardColorModal.modal.fade{:role => "dialog"}
  = simple_form_for CardColor.new, remote: true do |f|
    = f.input :user_generated, as: :hidden, input_html: { value: 1 }
    .modal-dialog.modal-sm
      .modal-content
        .modal-header
          %button.close{"data-dismiss" => "modal", :type => "button"} ×
          %h4.modal-title Custom color
        .modal-body
          = f.input :name
          = f.input :c
          = f.input :y
          = f.input :m
          = f.input :k
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
          = f.button :submit, "Save", class: 'btn btn-primary'

app/views/casino_card_art_requests/_form.html.haml
.container
  .panel.panel-primary
    .panel-heading
      %h3 Art Flow
    .panel-body
      %h4{:style => "text-align: center;"} Casion Cart Art Request
      = simple_nested_form_for([@art_request, @casino_card_art_request], :html => { :class => 'form-inline'}) do |f|
        = f.input :art_request_id, as: :hidden, input_html: {value: @art_request.id}
        = f.error_notification
        
        .row
          .col-md-4
            %b Customer # :
            = @art_request.customer_id
          .col-md-4
            Customer :
            = @art_request.customer_details
          .col-md-4
            Name :
            = @art_request.customer_name
        %br
        .row
          .col-md-offset-9.col-md-3
            %b Job No: P#{ArtRequest.count}
        %br
        .panel.panel-section
          .row
            .col-md-3
              = f.input :paper_type_id, collection: CardPaper.all
            .col-md-3
              = f.input :card_type_id, collection: CardFamily.all
        #specifications
          - @casino_card_art_request.art_request_specifications.build if @casino_card_art_request.art_request_specifications.empty?
          = f.fields_for :art_request_specifications do |s|
            .panel.panel-section
              %legend Specifications
              .row
                .col-md-3
                  .panel.panel-section
                    %legend Card Side
                    = s.input :card_side_id, :as => :radio_buttons, :collection => [ "Face", "Back" ], :item_wrapper_class => 'radio-inline', label: false
                .col-md-3
                  =s.input :face_style_id, collection: CardFace.all, include_blank: false
                .col-md-3.card-edge-type.default-hide
                  =s.input :card_edge_id, collection: CardEdge.all, include_blank: false 
                .col-md-3.packaging-type.default-hide
                  =s.input :card_packaging_type_id, collection: CardPackaging.all, include_blank: false
                .col-md-3.side-identifier 
              .panel.panel-section
                %legend.colors Face Colors
                .row
                  .col-md-3
                    = s.input :first_color_id, collection: available_colors , input_html: { class: 'specification_card_color'} 
                    %div.color-preview
                  .col-md-3
                    = s.input :second_color_id, collection: available_colors, input_html: { class: 'specification_card_color'} 
                    %div.color-preview
                  .col-md-3
                    = s.input :third_color_id, collection: available_colors, input_html: { class: 'specification_card_color'}
                    %div.color-preview
                  .col-md-3
                    = s.input :forth_color_id, collection: available_colors, input_html: { class: 'specification_card_color'}
                    %div.color-preview
              .panel.panel-section
                %legend Production Notes
                .row
                  .col-md-12
                    = s.input :production_notes, label: false, input_html: { :cols => 120, :rows => 3}
        .panel.panel-section-no-border
          .row
            - if @confirmation
              .col-md-4
                = link_to "OK", confirmation_art_request_casino_card_art_request_path(@art_request, @casino_card_art_request), class: 'btn btn-primary'
            - else
              .col-md-4
                = f.button :submit, "Save"
              .col-md-4
                = f.link_to_add "Add spefications", :art_request_specifications, class: 'btn btn-default center-block', "data-target" => "#specifications"
      = render "card_color_modal"
    .panel-footer

app/views/casino_card_art_requests/edit.html.haml
%h1 Editing casino card art request

= render 'form'

app/views/casino_card_art_requests/index.html.haml
%h1 Listing casino card art requests
= link_to 'New Casino card art request', new_art_request_casino_card_art_request_path(@art_request, @casino_card_art_request), class: 'btn btn-primary pull-right'

%table.table.table-bordered
  %thead
    %tr
      %th Customer
      %th Customer details
      %th Customer name
      %th Customer phone
      %th Customer email
      %th Job no
      %th Paper type
      %th Card type
      %th
      %th
      %th

  %tbody
    - @casino_card_art_requests.each do |casino_card_art_request|
      %tr
        %td= casino_card_art_request.art_request.customer_id if casino_card_art_request.art_request
        %td= casino_card_art_request.art_request.customer_details if casino_card_art_request.art_request
        %td= casino_card_art_request.art_request.customer_name if casino_card_art_request.art_request
        %td= casino_card_art_request.art_request.customer_phone if casino_card_art_request.art_request
        %td= casino_card_art_request.art_request.customer_email if casino_card_art_request.art_request
        %td= casino_card_art_request.job_no
        %td= casino_card_art_request.paper_type_id
        %td= casino_card_art_request.card_type_id
        %td= link_to 'Show', [@art_request, casino_card_art_request ]
        %td= link_to 'Edit', edit_art_request_casino_card_art_request_path(@art_request, casino_card_art_request)
        %td= link_to 'Destroy', [ @art_request, casino_card_art_request ], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/casino_card_art_requests/new.html.haml
= render 'form'

//= link_to 'Back', art_request_casino_card_art_requests_path(@art_request)

app/views/casino_card_art_requests/show.html.haml
%h3.text-center Casino Card Art Request Details 
.panel.panel-section
  .row
    .col-md-offset-9.col-md-3
      %p
        %b Job no:
        = @casino_card_art_request.job_no
  .row
    .col-md-3
      %p
        %b Customer #:
        = @casino_card_art_request.customer_id
    .col-md-3
      %p
        %b Customer:
        = @casino_card_art_request.customer_details
    .col-md-3
      %p
        %b Name:
        = @casino_card_art_request.customer_name
    .col-md-3
      %p
        %b Phone:
        = @casino_card_art_request.customer_phone
  .row
    .col-md-4
      %p
        %b Paper type:
        = @casino_card_art_request.paper_type.name if @casino_card_art_request.paper_type
    .col-md-4
      %p
        %b Card type:
        = @casino_card_art_request.card_type.name if @casino_card_art_request.card_type
- @casino_card_art_request.art_request_specifications.each do |specification|
  .panel.panel-section
    %h3 Specifications:
    .panel.panel-section
      .row
        .col-md-3
          %b Card Side :
          = specification.card_side_id
        .col-md-3
          %b Face Style :
          = specification.face_style.name if specification.face_style
        .col-md-3
          %b Card Edge : 
          = specification.card_edge.name if specification.card_edge
        .col-md-3
          %b Packaging : 
          = specification.card_packaging.name if specification.card_packaging
    .panel.panel-section
      .row
        .col-md-3
          %b First Color :
          = specification.first_color.name if specification.first_color
        .col-md-3
          %b Second Color :
          = specification.second_color.name if specification.second_color
        .col-md-3
          %b Third Color : 
          = specification.third_color.name if specification.third_color
        .col-md-3
          %b Forth Color : 
          = specification.forth_color.name if specification.forth_color
    .panel.panel-section
      .row
        .col-md-12
          %b Production notes :  
          = specification.production_notes

= link_to 'Edit', edit_art_request_casino_card_art_request_path(@art_request, @casino_card_art_request)
\|
= link_to 'Back', art_request_casino_card_art_requests_path(@art_request)